################################################################################
#
# TRIQS: a Toolbox for Research in Interacting Quantum Systems
#
# Copyright (C) 2016-2018, N. Wentzell
# Copyright (C) 2018-2019, The Simons Foundation
#   author: N. Wentzell
#
# TRIQS is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# TRIQS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# TRIQS. If not, see <http://www.gnu.org/licenses/>.
#
################################################################################

# Placeholder used for the git hashes when the package was installed from a
# built distribution (e.g. PyPI / `pip install`) rather than the TRIQS/cmake
# build path, where the real hashes are unavailable.
_PYPI_PLACEHOLDER = "pypi-package-install"

try:
    # TRIQS/cmake build path: _version.py is generated by CMake with the real
    # version string and git hashes (see _version.py.in).
    from ._version import version, triqs_hash, app4triqs_hash
except ImportError:
    # pip / PyPI install: no cmake-generated _version.py is shipped. Read the
    # version from the installed package metadata and use an informative
    # placeholder for the git hashes so callers never error.
    try:
        from importlib.metadata import version as _v, PackageNotFoundError
        version = _v(__package__.split(".")[0])
    except PackageNotFoundError:
        version = "unknown"
    triqs_hash = _PYPI_PLACEHOLDER
    app4triqs_hash = _PYPI_PLACEHOLDER


def show_version():
    print("\nYou are using app4triqs version %s\n" % version)


def show_git_hash():
    print("\nYou are using app4triqs git hash %s based on triqs git hash %s\n"
          % (app4triqs_hash, triqs_hash))
